### ISSUE TITLE
MGE xmed is masked 

### ISSUE THREAD

**Issue by zhouconghao** [moustakas/legacyhalos#158]
I am running a batch of tests on legacy survey DR9 and in the ellipse step some returns this error. 

`Rank 031 (6 / 31): /global/cfs/projectdirs/desi/users/zhouc/desidonuts/output/3962/39627878689672231 (index 974)
Traceback (most recent call last):
  File "/global/cfs/projectdirs/desi/users/zhouc/desidonuts/desi-donuts/legacyhalos/sv3.py", line 921, in call_ellipse
    data, galaxyinfo = read_multiband(
  File "/global/cfs/projectdirs/desi/users/zhouc/desidonuts/desi-donuts/legacyhalos/sv3.py", line 867, in read_multiband
    data = _build_multiband_mask(
  File "/global/cfs/projectdirs/desi/users/zhouc/desidonuts/desi-donuts/legacyhalos/sv3.py", line 520, in _build_multiband_mask
    mgegalaxy = find_galaxy(img, nblob=1, binning=1, quiet=False)
  File "/global/cfs/projectdirs/desi/users/zhouc/desidonuts/desi-donuts/legacyhalos/mge.py", line 243, in __init__
    self.second_moments(img, ind)
  File "/global/cfs/projectdirs/desi/users/zhouc/desidonuts/desi-donuts/legacyhalos/mge.py", line 332, in second_moments
    xmed1 = int(round(self.xmed))
TypeError: type MaskedConstant doesn't define __round__ method`

Upon first investigation, it seems that the `self.xmed` value is masked is the reason. Has anyone encountered this before?

**Comment by zhouconghao** [comment]
I think this is fixed when I switch to the most updated branch of `legacyhalos`.
